
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.2.9
  creationTimestamp: null
  name: awsmachinepools.exp.infrastructure.cluster.x-k8s.io
spec:
  group: exp.infrastructure.cluster.x-k8s.io
  names:
    categories:
    - cluster-api
    kind: AWSMachinePool
    listKind: AWSMachinePoolList
    plural: awsmachinepools
    singular: awsmachinepool
  scope: Namespaced
  versions:
  - name: v1alpha3
    schema:
      openAPIV3Schema:
        description: AWSMachinePool is the Schema for the awsmachinepools API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: AWSMachinePoolSpec defines the desired state of AWSMachinePool
            properties:
              additionalSecurityGroups:
                description: AdditionalSecurityGroups is an array of references to security groups that should be applied to the instance. These security groups would be set in addition to any security groups defined at the cluster level or in the actuator.
                items:
                  description: AWSResourceReference is a reference to a specific AWS resource by ID, ARN, or filters. Only one of ID, ARN or Filters may be specified. Specifying more than one will result in a validation error.
                  properties:
                    arn:
                      description: ARN of resource
                      type: string
                    filters:
                      description: 'Filters is a set of key/value pairs used to identify a resource They are applied according to the rules defined by the AWS API: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/Using_Filtering.html'
                      items:
                        description: Filter is a filter used to identify an AWS resource
                        properties:
                          name:
                            description: Name of the filter. Filter names are case-sensitive.
                            type: string
                          values:
                            description: Values includes one or more filter values. Filter values are case-sensitive.
                            items:
                              type: string
                            type: array
                        required:
                        - name
                        - values
                        type: object
                      type: array
                    id:
                      description: ID of resource
                      type: string
                  type: object
                type: array
              additionalTags:
                additionalProperties:
                  type: string
                description: Tags defines a map of tags.
                type: object
              autoScalingGroupName:
                type: string
              availabilityZones:
                items:
                  type: string
                type: array
              awsLaunchTemplate:
                description: AwsLaunchTemplate defines the desired state of AWSLaunchTemplate
                properties:
                  ami:
                    description: 'todo: use a helper'
                    properties:
                      arn:
                        description: ARN of resource
                        type: string
                      filters:
                        description: 'Filters is a set of key/value pairs used to identify a resource They are applied according to the rules defined by the AWS API: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/Using_Filtering.html'
                        items:
                          description: Filter is a filter used to identify an AWS resource
                          properties:
                            name:
                              description: Name of the filter. Filter names are case-sensitive.
                              type: string
                            values:
                              description: Values includes one or more filter values. Filter values are case-sensitive.
                              items:
                                type: string
                              type: array
                          required:
                          - name
                          - values
                          type: object
                        type: array
                      id:
                        description: ID of resource
                        type: string
                    type: object
                  blockDeviceMappings:
                    items:
                      description: BlockDeviceMappings from describe-launch-templates
                      properties:
                        deviceName:
                          type: string
                        ebs:
                          description: EBS from describe-launch-templates
                          properties:
                            encrypted:
                              type: boolean
                            volumeSize:
                              format: int64
                              type: integer
                            volumeType:
                              type: string
                          type: object
                      type: object
                    type: array
                  iamInstanceProfile:
                    type: string
                  id:
                    description: all the things needed for a launch template
                    type: string
                  instanceType:
                    description: 'InstanceType is the type of instance to create. Example: m4.xlarge'
                    type: string
                  name:
                    type: string
                  networkInterfaces:
                    items:
                      description: NetworkInterface from describe-launch-templates
                      properties:
                        deviceIndex:
                          format: int64
                          type: integer
                        groups:
                          items:
                            type: string
                          type: array
                      type: object
                    type: array
                  sshKeyName:
                    description: SSHKeyName is the name of the ssh key to attach to the instance. Valid values are empty string (do not use SSH keys), a valid SSH key name, or omitted (use the default SSH key name)
                    type: string
                  versionNumber:
                    format: int64
                    type: integer
                type: object
              defaultCooldown:
                type: integer
              desiredCapacity:
                type: integer
              healthCheckGracePeriod:
                type: integer
              healthCheckType:
                type: string
              maxSize:
                type: integer
              minSize:
                type: integer
              mixedInstancesPolicy:
                description: MixedInstancesPolicy from describe-auto-scaling-groups
                properties:
                  instancesDistribution:
                    description: InstancesDistribution from describe-auto-scaling-groups
                    properties:
                      onDemandAllocationStrategy:
                        type: string
                      onDemandBaseCapacity:
                        type: integer
                      onDemandPercentageAboveBaseCapacity:
                        type: integer
                      spotAllocationStrategy:
                        type: string
                    type: object
                  launchTemplate:
                    description: LaunchTemplate from describe-auto-scaling-groups
                    properties:
                      launchTemplateSpecification:
                        description: LaunchTemplateSpecification from describe-auto-scaling-groups
                        properties:
                          launchTemplateId:
                            type: string
                          launchTemplateName:
                            type: string
                          version:
                            type: string
                        type: object
                      overrides:
                        items:
                          description: Overrides from describe-auto-scaling-groups
                          properties:
                            InstanceType:
                              type: string
                          required:
                          - InstanceType
                          type: object
                        type: array
                    type: object
                type: object
              newInstancesProtectedFromScaleIn:
                type: boolean
              providerID:
                type: string
              providerIDList:
                description: ProviderIDList are the identification IDs of machine instances provided by the provider. This field must match the provider IDs as seen on the node objects corresponding to a machine pool's machine instances.
                items:
                  type: string
                type: array
              serviceLinkedRoleARN:
                type: string
              subnets:
                items:
                  type: string
                type: array
              terminationPolicies:
                items:
                  type: string
                type: array
              vpcZoneIdentifier:
                type: string
            type: object
          status:
            description: AWSMachinePoolStatus defines the observed state of AWSMachinePool
            properties:
              failureMessage:
                description: "ErrorMessage will be set in the event that there is a terminal problem reconciling the MachinePool and will contain a more verbose string suitable for logging and human consumption. \n This field should not be set for transitive errors that a controller faces that are expected to be fixed automatically over time (like service outages), but instead indicate that something is fundamentally wrong with the MachinePool's spec or the configuration of the controller, and that manual intervention is required. Examples of terminal errors would be invalid combinations of settings in the spec, values that are unsupported by the controller, or the responsible controller itself being critically misconfigured. \n Any transient errors that occur during the reconciliation of MachinePools can be added as events to the MachinePool object and/or logged in the controller's output."
                type: string
              failureReason:
                description: "ErrorReason will be set in the event that there is a terminal problem reconciling the MachinePool and will contain a succinct value suitable for machine interpretation. \n This field should not be set for transitive errors that a controller faces that are expected to be fixed automatically over time (like service outages), but instead indicate that something is fundamentally wrong with the MachinePool's spec or the configuration of the controller, and that manual intervention is required. Examples of terminal errors would be invalid combinations of settings in the spec, values that are unsupported by the controller, or the responsible controller itself being critically misconfigured. \n Any transient errors that occur during the reconciliation of MachinePools can be added as events to the MachinePool object and/or logged in the controller's output."
                type: string
              ready:
                description: Ready is true when the provider resource is ready.
                type: boolean
              replicas:
                description: Replicas is the most recently observed number of replicas.
                format: int32
                type: integer
            type: object
        type: object
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
